[app]
GOOGLE_API_KEY = "AIzaSyDqp64hDXg8FAEFHjxtPvLHslfTxP14nUs"
MONGODB_URI = "mongodb+srv://josueespinozasandoval482_db_user:mimongo123@cluster-davide.vvckh9g.mongodb.net/?appName=Cluster-DavidE"
USER = "Jorge David Espinoza Sandoval"
COHERE_API_KEY = "Jv4Uc6A7CY4UCy8pTtvPqfmzPGLjRcTYanj9Iwes"

[b2]
B2_BUCKET_NAME = "bucket-DE"
B2_READ_KEY_ID = "005079856b8f7d70000000004"
B2_READ_APPLICATION_KEY = "K005TVBbo06kmlvE0e/8P/5ESl5ELVY"
B2_WRITE_KEY_ID = "005079856b8f7d70000000002"
B2_WRITE_APPLICATION_KEY = "K00504Z4llsR//N/Ujs4p9dKiahqyqA"
